# Generated by Django 5.1.1 on 2024-10-07 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_talk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='img',
            field=models.ImageField(default='media/スクリーンショット_2024-09-19_22.46.28.png', upload_to='', verbose_name='アイコン'),
        ),
    ]
