# Generated by Django 5.1.1 on 2024-10-14 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_customuser_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='img',
            field=models.ImageField(default='media/一回前期_採点.JPEG', upload_to='', verbose_name='アイコン'),
        ),
    ]
